exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('profiles').del().then(function() {
    // Inserts seed entries
    return knex('profiles').insert([
      {
        firstname: 'Aaron',
        lastname: 'Caban',
        age: 13,
        gender: 'M',
        summary: '',
        characteristic1: 'Starbucks',
        characteristic2: 'cars',
        characteristic3: 'sports',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '3',
        created_at: '2017-12-28',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Abel',
        lastname: 'Hansen',
        age: 7,
        gender: 'M',
        summary: '',
        characteristic1: 'sports',
        characteristic2: 'video games',
        characteristic3: 'tv',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2018-05-21',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Agueda',
        lastname: 'Johnston',
        age: 18,
        gender: 'F',
        summary: '',
        characteristic1: 'Softball',
        characteristic2: 'mountains',
        characteristic3: '',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2017-10-23',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Alex',
        lastname: 'Collins',
        age: 17,
        gender: 'M',
        summary: '',
        characteristic1: 'VideoGames',
        characteristic2: 'music',
        characteristic3: 'walking',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2017-03-14',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Alexis',
        lastname: 'Ochoa',
        age: 13,
        gender: '',
        summary: '',
        characteristic1: 'Softball',
        characteristic2: 'shopping',
        characteristic3: 'eating',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '4', created_at: '2018-05-08',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Aliik "Trey"',
        lastname: 'Bomelyn-Holley',
        age: 9,
        gender: 'M',
        summary: '',
        characteristic1: 'Sports',
        characteristic2: 'Movies',
        characteristic3: 'Going Out to Eat',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '2', created_at: '2018-05-11',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Amariee ',
        lastname: 'Bell',
        age: 15,
        gender: 'M',
        summary: '',
        characteristic1: 'Action Movies',
        characteristic2: 'Reading',
        characteristic3: 'Writing',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '2', created_at: '2018-02-21',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Amber',
        lastname: 'Bryant',
        age: 16,
        gender: 'F',
        summary: '',
        characteristic1: 'Tutoring',
        characteristic2: '',
        characteristic3: '',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '2', created_at: '2016-02-15',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Andrew',
        lastname: 'Howell',
        age: 13,
        gender: 'M',
        summary: '',
        characteristic1: 'Video games',
        characteristic2: 'board games',
        characteristic3: '',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2017-09-28',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Angel',
        lastname: 'Ramirez',
        age: 10,
        gender: 'M',
        summary: '',
        characteristic1: 'Baseball',
        characteristic2: 'Spiderman',
        characteristic3: 'playing games',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '2', created_at: '2017-11-29',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Angie ',
        lastname: 'Apodaca-Godinez',
        age: 10,
        gender: 'F',
        summary: '',
        characteristic1: 'Being active',
        characteristic2: 'playing outside',
        characteristic3: 'running',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '4', created_at: '2018-04-19',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Anteveon',
        lastname: 'Warner',
        age: 17,
        gender: 'M',
        summary: '',
        characteristic1: 'Football',
        characteristic2: '',
        characteristic3: '',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2018-02-21',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Anthony',
        lastname: 'Brown',
        age: 16,
        gender: 'M',
        summary: '',
        characteristic1: 'Spiders',
        characteristic2: 'basketball',
        characteristic3: 'football',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2017-03-29',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Arielle',
        lastname: 'Chavez',
        age: 13,
        gender: 'F',
        summary: '',
        characteristic1: 'Sports',
        characteristic2: 'Reading',
        characteristic3: 'Arts and Crafts',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '2', created_at: '2018-03-13',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Benjamin',
        lastname: 'Love',
        age: 14,
        gender: 'M',
        summary: '',
        characteristic1: 'Video games',
        characteristic2: '',
        characteristic3: '',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2018-01-10',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Brayden ',
        lastname: 'Shirey',
        age: 15,
        gender: 'M',
        summary: '',
        characteristic1: 'Soccer',
        characteristic2: 'Video Games Wrestling',
        characteristic3: 'Rap Music',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '2', created_at: '2017-09-15',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Cha-reece',
        lastname: 'Altaha',
        age: 6,
        gender: 'F',
        summary: '',
        characteristic1: 'Art',
        characteristic2: 'watching TV',
        characteristic3: 'playing outside',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '4', created_at: '2018-04-09',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Christian ',
        lastname: 'McGee',
        age: 8,
        gender: 'M',
        summary: '',
        characteristic1: 'Soccer',
        characteristic2: 'basketball',
        characteristic3: 'playing outside',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '4', created_at: '2018-04-18',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Christopher',
        lastname: 'Guerrero',
        age: 9,
        gender: 'M',
        summary: '',
        characteristic1: 'Football',
        characteristic2: 'basketball',
        characteristic3: 'baseball',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '4', created_at: '2017-05-24',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Christopher',
        lastname: 'Darrow',
        age: 12,
        gender: 'M',
        summary: '',
        characteristic1: 'Baseball',
        characteristic2: 'Movies Video Games',
        characteristic3: 'Rap music',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '2', created_at: '2017-08-23',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Craig',
        lastname: 'Weatherspoon Jr',
        age: 10,
        gender: 'M',
        summary: '',
        characteristic1: 'Math',
        characteristic2: 'sports',
        characteristic3: 'football',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '2', created_at: '2017-11-30',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Damascus',
        lastname: 'Jackson',
        age: 8,
        gender: 'M',
        summary: '',
        characteristic1: 'Art',
        characteristic2: '',
        characteristic3: '',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2018-03-06',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Daniel',
        lastname: 'Myers',
        age: 12,
        gender: 'M',
        summary: '',
        characteristic1: 'Basketball',
        characteristic2: 'football',
        characteristic3: 'going out to eat',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2017-12-08',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Dareion',
        lastname: 'Burd',
        age: 13,
        gender: 'M',
        summary: '',
        characteristic1: 'Playing Guitar',
        characteristic2: 'Basketball',
        characteristic3: 'Games',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '3', created_at: '2017-11-15',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Daviontae',
        lastname: 'Howard',
        age: 11,
        gender: 'M',
        summary: '',
        characteristic1: 'dodgeball',
        characteristic2: 'star wars',
        characteristic3: '',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2018-03-06',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Desyre',
        lastname: 'Neighbors',
        age: 15,
        gender: 'F',
        summary: '',
        characteristic1: 'Basketball',
        characteristic2: 'Track',
        characteristic3: 'Volleyball',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '2', created_at: '2018-04-03',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Diamonique',
        lastname: 'Warner',
        age: 12,
        gender: 'F',
        summary: '',
        characteristic1: 'Basketball',
        characteristic2: '',
        characteristic3: '',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2018-02-21',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Edward',
        lastname: 'Quintana',
        age: 11,
        gender: 'M',
        summary: '',
        characteristic1: 'Sports',
        characteristic2: 'being outside',
        characteristic3: '',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2018-04-18',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Edwin',
        lastname: 'Hodges',
        age: 16,
        gender: 'M',
        summary: '',
        characteristic1: 'Sports',
        characteristic2: 'Being Active',
        characteristic3: 'Trampoline Park',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2016-10-11',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Elijah ',
        lastname: 'Scott',
        age: 18,
        gender: 'M',
        summary: '',
        characteristic1: 'MUSIC',
        characteristic2: 'making videos',
        characteristic3: 'YouTube',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '4', created_at: '2018-01-19',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Eva',
        lastname: 'Cervantez',
        age: 16,
        gender: 'F',
        summary: '',
        characteristic1: 'Sports',
        characteristic2: 'Dance',
        characteristic3: 'Boy Meets World',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '4', created_at: '2018-04-12',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Evan ',
        lastname: 'Gunderson',
        age: 12,
        gender: 'M',
        summary: '',
        characteristic1: 'Reading',
        characteristic2: 'beat boxing',
        characteristic3: 'youtube',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2018-05-30',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Feliciano',
        lastname: 'Murillo',
        age: 12,
        gender: 'M',
        summary: '',
        characteristic1: 'Football',
        characteristic2: 'basketball',
        characteristic3: 'history',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '1', created_at: '2018-04-30',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Francisco',
        lastname: 'Rache',
        age: 13,
        gender: 'M',
        summary: '',
        characteristic1: 'Video games',
        characteristic2: 'reading',
        characteristic3: 'hiking',
        need1: '',
        need2: '',
        need3: '',
        placement: '',
        placement_phone: '',
        placement_email: '',
        zone: '4', created_at: '2018-03-20',
        updated_at: '2018-06-08',
        assign_at: null
      }, {
        firstname: 'Gionna ', lastname: ' Goodlow ',  age: 10, gender: ' F ', summary: ' ', characteristic1: ' Basketball ', characteristic2: ' Castles n Coasters ', characteristic3: ' most fun activities ', need1: ' ', need2: ' ', need3: ' ', placement: ' ', placement_phone: ' ', placement_email: ' ', zone: ' 1 ', created_at: ' 2017-01-18 ', updated_at: ' 2018-06-08 ', assign_at: null},
 {
          firstname: 'Hansel',
          lastname: 'Perez',
          age: 17,
          gender: 'M',
          summary: '',
          characteristic1: 'boxing',
          characteristic2: 'football',
          characteristic3: 'basketball',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2016-12-18',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Isaiah',
          lastname: 'Arajon',
          age: 7,
          gender: 'M',
          summary: '',
          characteristic1: 'Playing outside',
          characteristic2: 'riding his bike',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-05-01',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Isaiah',
          lastname: 'Duran',
          age: 10,
          gender: 'M',
          summary: '',
          characteristic1: 'Electronics',
          characteristic2: 'Sports',
          characteristic3: 'Music',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-05-24',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Ivoryiiana',
          lastname: 'Horton',
          age: 14,
          gender: 'F',
          summary: '',
          characteristic1: 'Sports',
          characteristic2: 'Music',
          characteristic3: 'Movies',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2017-12-19',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Izabella',
          lastname: 'Pimintel',
          age: 14,
          gender: 'F',
          summary: '',
          characteristic1: 'Music',
          characteristic2: 'Cooking',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-04-17',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jacob',
          lastname: 'Tabur',
          age: 15,
          gender: 'M',
          summary: '',
          characteristic1: 'Legos',
          characteristic2: 'soccer',
          characteristic3: 'football',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2017-12-11',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jaivant',
          lastname: 'King',
          age: 15,
          gender: 'M',
          summary: '',
          characteristic1: 'going to the mall',
          characteristic2: 'out to eat',
          characteristic3: 'movies',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '3', created_at: '2018-01-08',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jalen',
          lastname: 'Phillips',
          age: 17,
          gender: 'M',
          summary: '',
          characteristic1: 'Basketball',
          characteristic2: 'Football',
          characteristic3: 'Movies',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-04-12',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jarell',
          lastname: 'Brooks',
          age: 14,
          gender: 'M',
          summary: '',
          characteristic1: 'basketball',
          characteristic2: 'skateboarding',
          characteristic3: 'bicycle',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2017-06-20',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jason',
          lastname: 'Nieves',
          age: 10,
          gender: 'M',
          summary: '',
          characteristic1: 'soccer',
          characteristic2: 'boxing',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2018-03-07',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jaylen',
          lastname: 'Harper',
          age: 12,
          gender: 'M',
          summary: '',
          characteristic1: 'VideoGames',
          characteristic2: '',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2017-11-05',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jayquan',
          lastname: 'Felder',
          age: 13,
          gender: 'M',
          summary: '',
          characteristic1: 'Basketball',
          characteristic2: 'Football',
          characteristic3: 'Video Games',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-04-12',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jenesis',
          lastname: 'Rios',
          age: 8,
          gender: 'F',
          summary: '',
          characteristic1: 'Playing with siblings ',
          characteristic2: 'riding her bike',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-05-01',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jerry',
          lastname: 'Bautista-Martinez',
          age: 9,
          gender: 'M',
          summary: '',
          characteristic1: 'Basketball',
          characteristic2: 'Power Rangers',
          characteristic3: 'Legos',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2017-11-14',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jessica',
          lastname: 'Daniels',
          age: 17,
          gender: 'F',
          summary: '',
          characteristic1: 'Sport',
          characteristic2: 'Music',
          characteristic3: 'Hiking',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2016-12-28',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Johnathan ',
          lastname: 'Jones',
          age: 16,
          gender: 'M',
          summary: '',
          characteristic1: 'Legos',
          characteristic2: 'Electronics',
          characteristic3: 'Reading',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2016-05-26',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jordan',
          lastname: 'Anglin',
          age: 16,
          gender: 'M',
          summary: '',
          characteristic1: 'Sports',
          characteristic2: 'Video Games',
          characteristic3: 'Drawing',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '4', created_at: '2017-04-03',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jordan',
          lastname: 'Bomelyn',
          age: 10,
          gender: 'M',
          summary: '',
          characteristic1: 'Arts and Crafts',
          characteristic2: 'Music',
          characteristic3: 'Sports',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-05-31',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Jose',
          lastname: 'Chavez Quinteros',
          age: 17,
          gender: 'M',
          summary: '',
          characteristic1: 'Music',
          characteristic2: 'Drawing',
          characteristic3: 'Jeopardy',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2016-08-13',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Joshua ',
          lastname: 'Goodlow',
          age: 11,
          gender: 'M',
          summary: '',
          characteristic1: 'Football',
          characteristic2: 'being active',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2018-05-03',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Juan',
          lastname: 'Bojorquez',
          age: 15,
          gender: 'M',
          summary: '',
          characteristic1: 'Rap',
          characteristic2: 'enchiladas',
          characteristic3: 'football',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2016-08-19',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Julian',
          lastname: 'Godinez-Apodaca',
          age: 12,
          gender: 'M',
          summary: '',
          characteristic1: 'Video games',
          characteristic2: 'being active',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2018-04-19',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Julian ',
          lastname: 'Pablo',
          age: 10,
          gender: 'M',
          summary: '',
          characteristic1: 'Ninjas',
          characteristic2: 'football',
          characteristic3: 'drawing',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2016-10-25',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Levi ',
          lastname: 'Weese',
          age: 12,
          gender: 'M',
          summary: '',
          characteristic1: 'Movies',
          characteristic2: 'Basketball',
          characteristic3: 'Playing on Tablet',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2017-11-14',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Lucerito',
          lastname: 'Guzman',
          age: 15,
          gender: 'F',
          summary: '',
          characteristic1: 'Drawing',
          characteristic2: '',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2018-04-25',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Luzclarita',
          lastname: 'Guzman',
          age: 12,
          gender: 'F',
          summary: '',
          characteristic1: 'loves school',
          characteristic2: 'art',
          characteristic3: 'drawing',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2018-04-25',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Marki',
          lastname: 'Anthony',
          age: 9,
          gender: 'M',
          summary: '',
          characteristic1: 'Computer games',
          characteristic2: 'sports',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2018-02-08',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Naomi',
          lastname: 'Hogan',
          age: 10,
          gender: 'M',
          summary: '',
          characteristic1: 'Playing outside',
          characteristic2: 'riding bicycles',
          characteristic3: 'playing games',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '3', created_at: '2018-04-09',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Oshae',
          lastname: 'Harville',
          age: 6,
          gender: 'M',
          summary: '',
          characteristic1: 'Baseball',
          characteristic2: 'Basketball',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-03-15',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Precious',
          lastname: 'Bufford',
          age: 17,
          gender: 'F',
          summary: '',
          characteristic1: 'Dancing',
          characteristic2: 'Basketball',
          characteristic3: 'Photography',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-05-14',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Raena',
          lastname: 'Dean',
          age: 15,
          gender: 'F',
          summary: '',
          characteristic1: 'Outings',
          characteristic2: 'Sports',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-03-29',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Remante',
          lastname: 'Baker',
          age: 17,
          gender: 'M',
          summary: '',
          characteristic1: 'Football',
          characteristic2: 'Wrestling',
          characteristic3: 'Track',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2017-08-23',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Rose ',
          lastname: 'Chavez',
          age: 15,
          gender: 'F',
          summary: '',
          characteristic1: 'Comics',
          characteristic2: 'Anime',
          characteristic3: 'Drawing',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-03-13',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Roy',
          lastname: 'Ruth Jr',
          age: 12,
          gender: 'M',
          summary: '',
          characteristic1: 'Baseball',
          characteristic2: 'Bowling',
          characteristic3: 'Math',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2016-12-28',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Sebastian',
          lastname: 'Rogers',
          age: 12,
          gender: 'M',
          summary: '',
          characteristic1: 'Football',
          characteristic2: 'basketball',
          characteristic3: 'video games',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2017-09-28',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Seth ',
          lastname: 'Hansen',
          age: 5,
          gender: 'M',
          summary: '',
          characteristic1: 'sports',
          characteristic2: 'video games',
          characteristic3: 'tv',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2018-05-21',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'TJ',
          lastname: 'Morris',
          age: 14,
          gender: 'M',
          summary: '',
          characteristic1: 'baseball',
          characteristic2: 'track',
          characteristic3: 'video games',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '4', created_at: '2017-01-12',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Treyveon',
          lastname: 'Wiggins',
          age: 16,
          gender: 'M',
          summary: '',
          characteristic1: 'Sports',
          characteristic2: 'Music',
          characteristic3: 'Movies',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2018-04-12',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Tristan',
          lastname: 'Buckley',
          age: 8,
          gender: 'M',
          summary: '',
          characteristic1: 'Soccer',
          characteristic2: 'Pizza',
          characteristic3: 'Del Taco',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2016-12-02',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Veronica ',
          lastname: 'Hamilton',
          age: 13,
          gender: 'F',
          summary: '',
          characteristic1: 'drawing',
          characteristic2: 'animals',
          characteristic3: 'and swimming',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '4', created_at: '2017-09-12',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Wesson',
          lastname: 'Kimmer',
          age: 10,
          gender: 'M',
          summary: '',
          characteristic1: 'Music',
          characteristic2: 'dancing',
          characteristic3: 'video games',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2018-02-26',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'William',
          lastname: 'Willis',
          age: 9,
          gender: 'M',
          summary: '',
          characteristic1: 'reptiles',
          characteristic2: 'football',
          characteristic3: 'working out',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2018-03-06',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Wyatt',
          lastname: 'Weese',
          age: 10,
          gender: 'M',
          summary: '',
          characteristic1: 'Soccer',
          characteristic2: 'Football',
          characteristic3: 'Basketball',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '2', created_at: '2017-11-14',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Yisrael',
          lastname: 'Valdez',
          age: 9,
          gender: 'M',
          summary: '',
          characteristic1: 'Sharks',
          characteristic2: 'Sports',
          characteristic3: 'Riding Bikes',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '4', created_at: '2017-04-05',
          updated_at: '2018-06-08',
          assign_at: null
        }, {
          firstname: 'Zeyron',
          lastname: 'Anthony',
          age: 12,
          gender: 'M',
          summary: '',
          characteristic1: 'Football',
          characteristic2: '',
          characteristic3: '',
          need1: '',
          need2: '',
          need3: '',
          placement: '',
          placement_phone: '',
          placement_email: '',
          zone: '1', created_at: '2018-02-20',
          updated_at: '2018-06-08',
          assign_at: null
        }
      ]);});
  };
